# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=127, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_email', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
