# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 06:27
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=account.models.generate_username, max_length=127, unique=True),
        ),
    ]
