# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-11 12:43
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=account.models.generate_activation_key, max_length=32, unique=True)),
            ],
        ),
    ]
