# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:40
from __future__ import unicode_literals

import account.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160215_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationToken',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activation_key', models.CharField(db_index=True, default=account.models.generate_activation_key, max_length=20, unique=True)),
            ],
        ),
    ]
