# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:46
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_activationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationtoken',
            name='activation_key',
            field=models.CharField(db_index=True, default=account.models.generate_activation_key, max_length=32, unique=True),
        ),
    ]
