# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20160216_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivationToken',
            new_name='VerificationToken',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified_email',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='verificationtoken',
            old_name='activation_key',
            new_name='token',
        ),
    ]
