# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 08:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.UUIDField(default=uuid.uuid4)),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('school', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('rating', django.contrib.postgres.fields.jsonb.JSONField(default={'accessibility': 0, 'attendance': 0, 'communication_skills': 0, 'efficiency': 0, 'fairness': 0, 'overall': 0})),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('staff_id', 'user_id')]),
        ),
    ]
