# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
