# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_pgjson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('text', models.TextField()),
                ('user_id', models.UUIDField()),
                ('files', django_pgjson.fields.JsonBField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('allow_publish', models.BooleanField(default=False)),
            ],
        ),
    ]
