# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
