# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='school',
            field=models.IntegerField(),
        ),
    ]
