# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20160426_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_id',
            new_name='id',
        ),
    ]
