# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20160426_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportvote',
            name='report_id',
        ),
    ]
