// User
export const USER_RECEIVE_REPORTS = 'USER_RECEIVE_REPORTS'

// Auth
export const AUTH_CHECK_TERMS = 'AUTH_CHECK_TERMS'
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS'
export const AUTH_CLEAR_FIELDS = 'AUTH_CLEAR_FIELDS'
export const AUTH_SUBMIT_LOADING = 'AUTH_SUBMIT_LOADING'
export const AUTH_SHOW_ERROR = 'AUTH_SHOW_ERROR'
export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
