// Buttons
export const BUTTON_SUBMIT_LOADING = 'BUTTON_SUBMIT_LOADING'

// Report/File
export const REPORT_CLEAR_FIELDS = 'REPORT_CLEAR_FIELDS'
export const REPORT_RECEIVE_SCHOOLS = 'REPORT_RECEIVE_SCHOOLS'
export const REPORT_RECEIVE_CATEGORIES = 'REPORT_RECEIVE_CATEGORIES'
export const REPORT_UPDATE_QUESTIONS = 'REPORT_UPDATE_QUESTIONS'
export const REPORT_UPDATE_ANSWER = 'REPORT_UPDATE_ANSWER'
export const REPORT_UPDATE_REPORT_FIELD = 'REPORT_UPDATE_REPORT_FIELD'
export const REPORT_UPDATE_CONTACT_FIELD = 'REPORT_UPDATE_CONTACT_FIELD'
export const REPORT_UPDATE_ATTACHMENT = 'REPORT_UPDATE_ATTACHMENT'
export const REPORT_SHOW_ERROR = 'REPORT_SHOW_ERROR'

// Report/View
export const REPORT_RECEIVE_ID = 'REPORT_RECEIVE_ID'
export const REPORT_RECEIVE_REPORT = 'REPORT_RECEIVE_REPORT'

// User
export const USER_RECEIVE_PROFILE = 'USER_RECEIVE_PROFILE'
export const USER_RECEIVE_REPORTS = 'USER_RECEIVE_REPORTS'

// Auth
export const AUTH_CHECK_TERMS = 'AUTH_CHECK_TERMS'
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS'
export const AUTH_CLEAR_FIELDS = 'AUTH_CLEAR_FIELDS'
export const AUTH_SHOW_ERROR = 'AUTH_SHOW_ERROR'
export const AUTH_UPDATE_FIELD = 'AUTH_UPDATE_FIELD'
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS'
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS'
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS'
